name: shared_preferences_explorer
description: "A Flutter package for on-screen viewing of shared_preferences. Supports SharedPreferences, SharedPreferencesAsync, and SharedPreferencesWithCache."
version: 0.3.0
repository: https://github.com/skw398/shared_preferences_explorer

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

screenshots:
  - description: "screenshot1"
    path: assets/screenshot1.png
  - description: "screenshot2"
    path: assets/screenshot2.png

topics:
  - shared-preferences
